export const GET_ALL_REPOS_REQUEST = 'GET_ALL_REPOS_REQUEST';
export const GET_ALL_REPOS_SUCCESS = 'GET_ALL_REPOS_SUCCESS';
export const GET_ALL_REPOS_ERROR = 'GET_ALL_REPOS_ERROR';

export const GET_SEARCH_RESULTS_REQUEST = 'GET_SEARCH_RESULTS_REQUEST';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR';